### ISSUE TITLE
I stock in login page when I use Udeler

### ISSUE THREAD

**Issue by noamangg** [rk23597/udemy-downloader-gui#15]
I stock in login page when I use it when I press login it opens a new window then I login into my Udemy account put nothing happened
it opens like this
![Screenshot (171)](https://user-images.githubusercontent.com/71488276/148095377-a1d76b1d-b831-4487-a8ec-690f8a95d7d9.png)

**Comment by cristhianA94** [comment]
I have a same problem! Plis update

**Comment by rajhlinux** [comment]
I got the same issue, i login and no download feature... are they stealing passwords?

**Comment by ItsJuSTleU** [comment]
Check the updated version here.
https://github.com/FaisalUmair/udemy-downloader-gui
